name: Prod Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://portal.azure.com/
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        working-directory: infra/envs/prod
        run: terraform init

      - name: Terraform Plan
        working-directory: infra/envs/prod
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        working-directory: infra/envs/prod
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
