name: UAT Deployment

on:
  push:
    branches:
      - uat

jobs:
  deploy-uat:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    environment:
      name: uat
      url: https://portal.azure.com/

    defaults:
      run:
        working-directory: azure-terraform/envs/uat

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="terraform.tfvars"
